### ISSUE TITLE
Missing file uavcan/Timestamp.hpp

### ISSUE THREAD

**Issue by jpkh** [UAVCAN/uavcan#16]
Looks like one of the missing file is missing. We try to compile UAVCAN libraries but Timestamp.hpp file is missing from repository. Please check that all files are correct. Timestamp.hpp is included from uavcan/time.hpp file.

**Comment by pavel-kirienko** [comment]
This file is supposed to be generated by the DSDL compiler. Probably the compiler doesn't work in your case. Are you sure you have Python installed?

**Comment by jpkh** [comment]
Will check our computers then and dev. environment.
