### ISSUE TITLE
Using correct version of pyuavcan from libuavcan_dsdlc

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/uavcan#18]
`libuavcan_dsdlc` shall use source version of pyuavcan when available. Otherwise, wrong version of pyuavcan may be used for code generation, which may produce incompatible code.

Possible fix is to replace appending to `sys.path` with prepending [here](https://github.com/UAVCAN/uavcan/blob/master/libuavcan/dsdl_compiler/libuavcan_dsdlc#L12-L17).

@bendyer

**Comment by bendyer** [comment]
Reproduced the original issue I had with current master and confirmed fix:
• Cleaned repo;
• Made a change to pyuavcan which would yield incorrect data type signatures;
• Ran `mkdir build && cd build && cmake .. && make && sudo make install`;
• Verified type signatures were incorrect;
• Reverted pyuavcan change;
• Ran `rm -rf build/* && cd build && cmake .. && make`;
• Verified type signatures were still incorrect;
• Applied change from PR #20;
• Ran `rm -rf build/* && cd build && cmake .. && make`;
• Verified type signatures were correct.
