### ISSUE TITLE
Service invocation response cannot be empty

### ISSUE THREAD

**Issue by antoinealb** [UAVCAN/uavcan#23]
I tried using the following message, which results in a static assert failing:

```
float16 test
---
```

Changing it to the following fixed the problem.

```
float16 test
---
float16 dummy
```

I did not see anything preventing service invocation response from being empty in the spec. If this is intended, it should be added to the documentation and it would be nice if the DSDL compiler displayed an error / warning.

**Comment by pavel-kirienko** [comment]
Thanks for reporting! Fixed in https://github.com/UAVCAN/uavcan/commit/2dbf8cd43280651a04e2559f0679dba2d7543fc3.
