### ISSUE TITLE
Implement POSIX file server backend

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/uavcan#28]
@davids5 Can you help with it?

Here's the backend interface: https://github.com/UAVCAN/uavcan/blob/dynamic_node_id_raft/libuavcan/include/uavcan/protocol/file_server.hpp#L24. For the firmware update server we'll need at least `getInfo()` and `read()`.

The backend class should go into `libuavcan_drivers/posix/include/uavcan_posix/file_server_backend.hpp`.

https://github.com/UAVCAN/uavcan/pull/27 needs to be merged first.

**Comment by davids5** [comment]
Hi Pavel,

 

This has been pushed.

 

David

**Comment by pavel-kirienko** [comment]
Great, thank you!

A few questions:

1. You defined a new string type - [PathString](https://github.com/UAVCAN/uavcan/blob/dynamic_node_id_raft/libuavcan_drivers/posix/include/uavcan_posix/file_server_backend.hpp#L43), of max length (200+128) bytes. That's a lot. Since we're concerned about memory use, are you sure we need prefixes that long? Couldn't we keep it at 200 bytes long? This would allow to re-use the existing string type - `IFileServerBackend::Path` - for the prefix, which should also reduce code bloat because of fewer instantiations of the string template.

2. [Here](https://github.com/UAVCAN/uavcan/blob/dynamic_node_id_raft/libuavcan_drivers/posix/include/uavcan_posix/file_server_backend.hpp#L93) we should also set flags `FLAG_READABLE` and `FLAG_WRITEABLE`, until proper permission checks are implemented.

3. Return codes are different from the rest of the library; I failed to document it properly in the interface description (will fix that). See https://github.com/UAVCAN/uavcan/blob/master/dsdl/uavcan/protocol/file/Error.uavcan#L9
