### ISSUE TITLE
Consider a low rate call into the FileServer for Garbage collection

### ISSUE THREAD

**Issue by davids5** [UAVCAN/uavcan#36]
@pavel-kirienko   

The file cache expires entrees as  needed when Read is called. But if no reads are occurring and a node does not read the complete file we can have expired entries that are not released (uses memory and  FD)

It would be nice to add a tick that would be called every 1-10 minutes to expire any dangling cache entries.

**Comment by pavel-kirienko** [comment]
You could use `TimerBase` to implement this. See:

- https://github.com/UAVCAN/uavcan/blob/master/libuavcan/include/uavcan/node/timer.hpp#L46
- http://uavcan.org/Libuavcan_tutorials:_Using_timers
